name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - run: |
        mkdir -p /etc/nginx
        sudo cp .github/actions/check404/nginx.conf /etc/nginx/
        sudo apt-get update
        sudo apt-get install nginx
        #sudo systemctl start nginx
        sudo service nginx start
        curl -I localhost
    - uses: actions/setup-node@v1
    - run: | 
        cd docs/guide/website
        yarn
        yarn build

