name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - run: |
        sudo apt-get update
        sudo apt-get install nginx
        mkdir -p /etc/nginx
        sudo cp .github/actions/check404/nginx.conf /etc/nginx/
        #sudo systemctl start nginx
    - run: | 
        cd docs/guide/website
        yarn
        yarn build
        sudo cp -a build/botpress-docs/. /usr/share/nginx/html/
    - run: | 
        sudo service nginx start
        curl localhost


