name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - run: |
        sudo apt-get update
        sudo apt-get install nginx
        mkdir -p /etc/nginx
        sudo cp .github/actions/check404/nginx.conf /etc/nginx/
    - run: | 
        cd docs/guide/website
        yarn
        yarn build
        sudo cp -a build/botpress-docs/. /usr/share/nginx/html/
    - run: |
        sudo service nginx restart
        curl localhost
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' # (x64 or x86)
    - run: |
        python --version
        pip install scrapy
        scrapy runspider -o items1.csv -a site="http://localhost" .github/actions/check404/spider.py -s HTTPERROR_ALLOW_ALL=True
    


