name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - run: |
        sudo apt-get update
        sudo apt-get install nginx
        sudo service nginx start  
    - uses: actions/setup-node@v1
    - run: | 
        cd docs/guide/website
        yarn
        yarn build

